// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDA796uECT74K3IuRBmPXYw2wp6kb3fjE',
    appId: '1:70971161005:web:b3ca5a754fb086b8608924',
    messagingSenderId: '70971161005',
    projectId: 'phan-family',
    authDomain: 'phan-family.firebaseapp.com',
    storageBucket: 'phan-family.firebasestorage.app',
    measurementId: 'G-FC2DLJEL0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqZQCl2D0ZVY3EXgFlkX45GALBYkldb8',
    appId: '1:70971161005:android:7b63f6575c1d0546608924',
    messagingSenderId: '70971161005',
    projectId: 'phan-family',
    storageBucket: 'phan-family.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABsk2iviGZMTE1T2QJxddC1aGS-3I6Iig',
    appId: '1:70971161005:ios:0870c227d3d6c8d7608924',
    messagingSenderId: '70971161005',
    projectId: 'phan-family',
    storageBucket: 'phan-family.firebasestorage.app',
    iosBundleId: 'com.phan.phanFamily',
  );
}
