import 'package:cloud_firestore/cloud_firestore.dart';
import 'models/meal_model.dart';
import 'services/household_service.dart';

class SeedData {
  static Future<void> importMeals() async {
    final service = HouseholdService();
    
    // Kiểm tra xem đã có data chưa để tránh duplicate
    final snapshot = await FirebaseFirestore.instance.collection('meals').limit(1).get();
    if (snapshot.docs.isNotEmpty) {
      print('Data already exists!');
      return;
    }

    print('Starting to seed 30 meals...');

    final List<MealModel> meals = [
      // ==========================================
      // 20 MÓN MẶN (MAIN)
      // ==========================================
      MealModel(
        id: '',
        name: 'Thịt kho tàu',
        description: 'Thịt ba chỉ kho trứng cút mềm rục, đậm đà vị quê hương.',
        imageUrl: 'https://images.unsplash.com/photo-1626804475297-41609ea0f488?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'pork',
        mealType: 'main',
        prepTime: 15,
        cookTime: 45,
        servings: 4,
        estimatedCost: 120000,
        difficulty: 'medium',
        tags: ['truyền thống', 'đậm đà'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 550, protein: 30, carbs: 10, fat: 40, sodium: 800),
        ingredients: [
          IngredientModel(id: 'i1', name: 'Thịt ba chỉ', quantity: 500, unit: 'g'),
          IngredientModel(id: 'i2', name: 'Trứng cút', quantity: 15, unit: 'quả'),
          IngredientModel(id: 'i3', name: 'Nước dừa tươi', quantity: 300, unit: 'ml'),
          IngredientModel(id: 'i4', name: 'Nước mắm', quantity: 3, unit: 'thìa'),
          IngredientModel(id: 'i5', name: 'Đường', quantity: 2, unit: 'thìa'),
        ],
        instructions: [
          'Thịt ba chỉ rửa sạch, thái miếng vuông.',
          'Ướp thịt với nước mắm, đường, hành tím băm trong 30 phút.',
          'Luộc chín trứng cút và bóc vỏ.',
          'Thắng đường làm nước màu, cho thịt vào xào săn.',
          'Đổ nước dừa vào nồi, đun sôi rồi hạ nhỏ lửa.',
          'Kho khoảng 30 phút cho thịt mềm, thêm trứng cút vào kho thêm 15 phút.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Gà kho gừng',
        description: 'Thịt gà kho đậm đà, thơm lừng vị gừng tươi ấm bụng.',
        imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'chicken',
        mealType: 'main',
        prepTime: 15,
        cookTime: 30,
        servings: 4,
        estimatedCost: 90000,
        difficulty: 'easy',
        tags: ['ấm bụng', 'dễ làm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 320, protein: 35, carbs: 5, fat: 15, sodium: 700),
        ingredients: [
          IngredientModel(id: 'i6', name: 'Thịt gà', quantity: 500, unit: 'g'),
          IngredientModel(id: 'i7', name: 'Gừng', quantity: 50, unit: 'g'),
          IngredientModel(id: 'i8', name: 'Nước mắm', quantity: 2, unit: 'thìa'),
          IngredientModel(id: 'i9', name: 'Đường', quantity: 1, unit: 'thìa'),
        ],
        instructions: [
          'Gà chặt miếng vừa ăn, rửa sạch với muối.',
          'Gừng gọt vỏ, thái sợi hoặc đập dập.',
          'Ướp gà với mắm, đường, tiêu, và một nửa lượng gừng.',
          'Phi thơm tỏi và gừng còn lại, cho gà vào xào săn.',
          'Thêm chút nước, hạ nhỏ lửa kho đến khi nước sệt lại.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Cá rô phi chiên giòn',
        description: 'Cá rô phi phi lê chiên giòn rụm, chấm nước mắm tỏi ớt.',
        imageUrl: 'https://images.unsplash.com/photo-1599081577741-6949397f26d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'fish',
        mealType: 'main',
        prepTime: 10,
        cookTime: 15,
        servings: 4,
        estimatedCost: 70000,
        difficulty: 'easy',
        tags: ['nhanh gọn', 'trẻ em thích'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 280, protein: 25, carbs: 0, fat: 18, sodium: 300),
        ingredients: [
          IngredientModel(id: 'i10', name: 'Cá rô phi (nguyên con hoặc phi lê)', quantity: 800, unit: 'g'),
          IngredientModel(id: 'i11', name: 'Bột chiên giòn', quantity: 1, unit: 'gói'),
          IngredientModel(id: 'i12', name: 'Dầu ăn', quantity: 200, unit: 'ml'),
        ],
        instructions: [
          'Cá làm sạch, khía vài đường trên mình cá (nếu để nguyên con).',
          'Tẩm cá qua một lớp bột chiên giòn mỏng.',
          'Đun sôi dầu, thả cá vào chiên ngập dầu trên lửa vừa.',
          'Khi cá vàng giòn hai mặt thì vớt ra để ráo dầu.',
          'Làm nước mắm tỏi ớt chua ngọt để chấm kèm.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Sườn xào chua ngọt',
        description: 'Sườn non mềm ngọt quyện sốt chua chua ngọt ngọt bắt cơm.',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-811114215443?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'pork',
        mealType: 'main',
        prepTime: 15,
        cookTime: 25,
        servings: 4,
        estimatedCost: 150000,
        difficulty: 'medium',
        tags: ['ngon miệng', 'bắt cơm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 450, protein: 28, carbs: 20, fat: 30, sodium: 600),
        ingredients: [
          IngredientModel(id: 'i13', name: 'Sườn non', quantity: 500, unit: 'g'),
          IngredientModel(id: 'i14', name: 'Cà chua', quantity: 2, unit: 'quả'),
          IngredientModel(id: 'i15', name: 'Hành tây', quantity: 1, unit: 'củ'),
          IngredientModel(id: 'i16', name: 'Giấm gạo', quantity: 2, unit: 'thìa'),
          IngredientModel(id: 'i17', name: 'Đường', quantity: 2, unit: 'thìa'),
        ],
        instructions: [
          'Sườn chặt miếng vừa ăn, chần sơ qua nước sôi rồi rửa sạch.',
          'Chiên sườn hơi vàng xém các mặt.',
          'Cà chua thái hạt lựu, hành tây thái múi cau.',
          'Xào cà chua nhuyễn, thêm giấm, đường, nước mắm, chút nước tạo thành sốt chua ngọt.',
          'Cho sườn và hành tây vào đảo đều rim nhỏ lửa 10 phút cho ngấm gia vị.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Thịt bò xào cần tỏi',
        description: 'Thịt bò mềm xào với cần tây, tỏi tây thơm lừng.',
        imageUrl: 'https://images.unsplash.com/photo-1579294271881-300fae0050d2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'beef',
        mealType: 'main',
        prepTime: 15,
        cookTime: 10,
        servings: 4,
        estimatedCost: 140000,
        difficulty: 'easy',
        tags: ['nhanh gọn', 'giàu sắt'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 350, protein: 32, carbs: 8, fat: 18, sodium: 400),
        ingredients: [
          IngredientModel(id: 'i18', name: 'Thịt bò', quantity: 300, unit: 'g'),
          IngredientModel(id: 'i19', name: 'Cần tây', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i20', name: 'Tỏi tây', quantity: 100, unit: 'g'),
          IngredientModel(id: 'i21', name: 'Tỏi băm', quantity: 1, unit: 'thìa'),
        ],
        instructions: [
          'Thịt bò thái mỏng, ướp với chút dầu hào, tỏi băm, tiêu và dầu ăn.',
          'Cần tây, tỏi tây rửa sạch, cắt khúc.',
          'Phi thơm tỏi, cho thịt bò vào xào lửa lớn nhanh tay, bò vừa chín tới thì trút ra đĩa.',
          'Dùng chảo đó xào cần tây tỏi tây cho chín tới, nêm chút gia vị.',
          'Đổ thịt bò vào đảo nhanh đều rồi tắt bếp.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Đậu hũ dồn thịt sốt cà',
        description: 'Đậu hũ chiên bọc nhân thịt băm, sốt cà chua chua ngọt ngọt.',
        imageUrl: 'https://images.unsplash.com/photo-1625938146369-adc83368bda7?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'pork',
        mealType: 'main',
        prepTime: 20,
        cookTime: 25,
        servings: 4,
        estimatedCost: 85000,
        difficulty: 'medium',
        tags: ['thanh đạm', 'truyền thống'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 400, protein: 25, carbs: 12, fat: 28, sodium: 500),
        ingredients: [
          IngredientModel(id: 'i22', name: 'Đậu hũ chiên', quantity: 6, unit: 'miếng'),
          IngredientModel(id: 'i23', name: 'Thịt heo xay', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i24', name: 'Nấm mèo', quantity: 20, unit: 'g'),
          IngredientModel(id: 'i25', name: 'Cà chua', quantity: 3, unit: 'quả'),
        ],
        instructions: [
          'Nấm mèo ngâm nở, băm nhỏ trộn với thịt xay, hành tím, gia vị.',
          'Rạch 1 đường trên miếng đậu, nhồi nhân thịt vào.',
          'Cà chua băm nhuyễn. Đem chiên sơ đậu dồn thịt.',
          'Phi hành tỏi xào cà chua cho nhuyễn, thêm xíu nước tạo sốt.',
          'Cho đậu dồn thịt vào sốt, rim lửa nhỏ 10 phút.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Trứng chiên thịt băm',
        description: 'Món ăn siêu nhanh gọn, dễ ăn cho những ngày bận rộn.',
        imageUrl: 'https://images.unsplash.com/photo-1582169505937-b9992bd01ed9?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'egg',
        mealType: 'main',
        prepTime: 5,
        cookTime: 10,
        servings: 4,
        estimatedCost: 45000,
        difficulty: 'easy',
        tags: ['siêu nhanh', 'tiết kiệm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 300, protein: 20, carbs: 2, fat: 22, sodium: 400),
        ingredients: [
          IngredientModel(id: 'i26', name: 'Trứng gà', quantity: 4, unit: 'quả'),
          IngredientModel(id: 'i27', name: 'Thịt heo xay', quantity: 150, unit: 'g'),
          IngredientModel(id: 'i28', name: 'Hành lá', quantity: 10, unit: 'g'),
        ],
        instructions: [
          'Thịt xay ướp xíu hạt nêm, tiêu, hành tím băm.',
          'Trứng đập ra tô, đánh tan cùng hành lá cắt nhỏ và chút nước mắm.',
          'Xào thịt băm trên chảo cho chín tới.',
          'Đổ trứng vào chảo tráng đều mặt thịt, đậy nắp lửa nhỏ.',
          'Trứng chín vàng đều, lật mặt hoặc gập đôi tùy thích.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Mực xào chua ngọt',
        description: 'Mực tươi xào với dứa, cà chua, cần tây chua ngọt đậm vị.',
        imageUrl: 'https://images.unsplash.com/photo-1634629477028-c518b0683070?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'seafood',
        mealType: 'main',
        prepTime: 15,
        cookTime: 10,
        servings: 4,
        estimatedCost: 180000,
        difficulty: 'medium',
        tags: ['hải sản', 'tươi mát'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 250, protein: 22, carbs: 15, fat: 10, sodium: 550),
        ingredients: [
          IngredientModel(id: 'i29', name: 'Mực ống', quantity: 400, unit: 'g'),
          IngredientModel(id: 'i30', name: 'Dứa (thơm)', quantity: 0.5, unit: 'quả'),
          IngredientModel(id: 'i31', name: 'Cà chua', quantity: 2, unit: 'quả'),
          IngredientModel(id: 'i32', name: 'Cần tây, hành tây', quantity: 100, unit: 'g'),
        ],
        instructions: [
          'Mực làm sạch, khứa vẩy rồng, thái miếng vừa ăn, chần qua nước sôi 30 giây.',
          'Dứa, cà chua, hành tây thái múi cau.',
          'Phi tỏi thơm, xào hành tây, dứa, cà chua cho hơi mềm.',
          'Đổ mực vào xào nhanh lửa lớn, nêm mắm, đường, hạt nêm.',
          'Cuối cùng rắc cần tây, đảo đều tắt bếp.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Tôm rang thịt ba chỉ',
        description: 'Tôm rim cùng thịt ba chỉ mằn mặn, ngọt ngọt, ăn bao hao cơm.',
        imageUrl: 'https://images.unsplash.com/photo-1560684352-8497838a2229?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'seafood',
        mealType: 'main',
        prepTime: 15,
        cookTime: 20,
        servings: 4,
        estimatedCost: 160000,
        difficulty: 'easy',
        tags: ['đậm đà', 'bắt cơm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 420, protein: 26, carbs: 10, fat: 30, sodium: 650),
        ingredients: [
          IngredientModel(id: 'i33', name: 'Tôm sú hoặc tôm đất', quantity: 300, unit: 'g'),
          IngredientModel(id: 'i34', name: 'Thịt ba chỉ', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i35', name: 'Hành tím, tỏi', quantity: 20, unit: 'g'),
          IngredientModel(id: 'i36', name: 'Nước mắm, đường, tiêu', quantity: 1, unit: 'lượng vừa đủ'),
        ],
        instructions: [
          'Tôm cắt râu, rửa sạch. Thịt ba chỉ thái lát mỏng.',
          'Cho thịt ba chỉ vào chảo rang cháy cạnh ra bớt mỡ.',
          'Cho tôm vào rang cùng thịt tới khi vỏ tôm chuyển đỏ.',
          'Nêm nước mắm, đường, bột ngọt, chút nước màu.',
          'Rim lửa nhỏ tới khi cạn nước, tôm thịt kẹo lại, rắc tiêu.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Gà chiên nước mắm',
        description: 'Cánh gà chiên giòn, áo lớp nước mắm tỏi đậm vị.',
        imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'chicken',
        mealType: 'main',
        prepTime: 15,
        cookTime: 25,
        servings: 4,
        estimatedCost: 110000,
        difficulty: 'medium',
        tags: ['chiên', 'trẻ em thích'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 450, protein: 25, carbs: 15, fat: 30, sodium: 850),
        ingredients: [
          IngredientModel(id: 'i37', name: 'Cánh gà', quantity: 500, unit: 'g'),
          IngredientModel(id: 'i38', name: 'Bột chiên giòn', quantity: 2, unit: 'thìa'),
          IngredientModel(id: 'i39', name: 'Tỏi băm', quantity: 2, unit: 'thìa'),
          IngredientModel(id: 'i40', name: 'Nước mắm, đường', quantity: 3, unit: 'thìa'),
        ],
        instructions: [
          'Cánh gà rửa muối, chặt làm đôi, để ráo. Xóc cánh gà với lớp mỏng bột chiên giòn.',
          'Chiên gà ngập dầu tới khi vàng giòn, vớt ra thấm dầu.',
          'Pha sốt: 2 mắm, 2 đường, 1 tương ớt, 1 nước.',
          'Phi thơm nhiều tỏi băm, đổ sốt vào đun sệt.',
          'Cho cánh gà vào đảo nhanh tay để sốt bám đều, tắt bếp.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Thịt luộc cà pháo mắm tôm',
        description: 'Món ăn mùa hè chuẩn vị Bắc.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'pork',
        mealType: 'main',
        prepTime: 5,
        cookTime: 25,
        servings: 4,
        estimatedCost: 90000,
        difficulty: 'easy',
        tags: ['mùa hè', 'đơn giản'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 400, protein: 20, carbs: 5, fat: 35, sodium: 700),
        ingredients: [
          IngredientModel(id: 'i41', name: 'Thịt ba chỉ', quantity: 500, unit: 'g'),
          IngredientModel(id: 'i42', name: 'Cà pháo muối', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i43', name: 'Mắm tôm', quantity: 2, unit: 'thìa'),
          IngredientModel(id: 'i44', name: 'Chanh, tỏi, ớt', quantity: 1, unit: 'lượng vừa đủ'),
        ],
        instructions: [
          'Thịt rửa sạch, đem luộc chín với 1 củ hành đập dập và chút muối.',
          'Thịt chín vớt ra ngâm vào âu nước lạnh cho trắng và giòn.',
          'Thái thịt thành từng lát mỏng.',
          'Pha mắm tôm với đường, nước cốt chanh, đánh bọt, thêm ớt tỏi băm.',
          'Dọn thịt ăn kèm cà pháo muối chua giòn.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Bò xào hành tây',
        description: 'Bò xào hành tây truyền thống, siêu nhanh gọn.',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-811114215443?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', // placeholder
        category: 'beef',
        mealType: 'main',
        prepTime: 10,
        cookTime: 10,
        servings: 4,
        estimatedCost: 130000,
        difficulty: 'easy',
        tags: ['nhanh', 'tiện lợi'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 320, protein: 30, carbs: 12, fat: 15, sodium: 400),
        ingredients: [
          IngredientModel(id: 'i45', name: 'Thịt bò', quantity: 300, unit: 'g'),
          IngredientModel(id: 'i46', name: 'Hành tây', quantity: 2, unit: 'củ'),
        ],
        instructions: [
          'Thịt bò thái mỏng ướp tỏi, dầu hào.',
          'Hành tây bổ múi cau.',
          'Xào thịt bò chín tới, trút ra bát.',
          'Xào hành tây nhanh tay cho chín tới, đổ bò vào đảo lại.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Chả lụa kho tiêu',
        description: 'Món kho biến tấu từ chả lụa mua sẵn, siêu ngon và tiết kiệm.',
        imageUrl: 'https://images.unsplash.com/photo-1582169505937-b9992bd01ed9?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'pork',
        mealType: 'main',
        prepTime: 5,
        cookTime: 15,
        servings: 4,
        estimatedCost: 65000,
        difficulty: 'easy',
        tags: ['lười', 'tiết kiệm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 300, protein: 18, carbs: 10, fat: 20, sodium: 650),
        ingredients: [
          IngredientModel(id: 'i47', name: 'Chả lụa', quantity: 300, unit: 'g'),
          IngredientModel(id: 'i48', name: 'Hành lá, tiêu sọ', quantity: 1, unit: 'lượng nhỏ'),
          IngredientModel(id: 'i49', name: 'Nước mắm, đường', quantity: 2, unit: 'thìa'),
        ],
        instructions: [
          'Chả lụa cắt miếng tam giác hoặc con cờ nhỏ vừa ăn.',
          'Phi thơm hành, cho chả vào xào sơ.',
          'Thêm nước mắm, đường, xíu nước và thật nhiều tiêu sọ đập dập.',
          'Rim keo lại, rắc hành lá.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Trứng cút sốt chua ngọt',
        description: 'Trứng cút chiên giòn áo sốt chua ngọt bắt mắt.',
        imageUrl: 'https://images.unsplash.com/photo-1625938146369-adc83368bda7?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'egg',
        mealType: 'main',
        prepTime: 10,
        cookTime: 15,
        servings: 4,
        estimatedCost: 40000,
        difficulty: 'easy',
        tags: ['trẻ con', 'rẻ'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 250, protein: 12, carbs: 15, fat: 18, sodium: 300),
        ingredients: [
          IngredientModel(id: 'i50', name: 'Trứng cút', quantity: 30, unit: 'quả'),
          IngredientModel(id: 'i51', name: 'Tương cà, mắm, đường', quantity: 3, unit: 'thìa'),
        ],
        instructions: [
          'Trứng cút luộc chín bóc vỏ.',
          'Chiên sơ trứng cút qua dầu để tạo lớp vỏ dai.',
          'Pha sốt chua ngọt: tương cà, giấm, đường, mắm.',
          'Đun sôi sốt rồi thả trứng cút vào đảo đều tới khi kẹo lại.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Đậu cove xào thịt heo',
        description: 'Đậu cove xào giòn ngọt với thịt heo thái mỏng.',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-811114215443?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'vegetable',
        mealType: 'main',
        prepTime: 10,
        cookTime: 10,
        servings: 4,
        estimatedCost: 75000,
        difficulty: 'easy',
        tags: ['rau củ', 'dễ làm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 280, protein: 18, carbs: 12, fat: 16, sodium: 400),
        ingredients: [
          IngredientModel(id: 'i52', name: 'Đậu cove', quantity: 300, unit: 'g'),
          IngredientModel(id: 'i53', name: 'Thịt heo', quantity: 150, unit: 'g'),
        ],
        instructions: [
          'Đậu cove tước xơ, cắt xéo mỏng hoặc để nguyên cọng dài.',
          'Thịt heo thái mỏng ướp mắm tiêu.',
          'Xào thịt heo vừa chín, cho đậu cove vào xào cùng.',
          'Nêm nếm gia vị, xào lửa lớn thêm 3 phút cho đậu giòn.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Ếch xào lăn',
        description: 'Ếch xào sả ớt nước cốt dừa béo ngậy thơm lừng.',
        imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'other',
        mealType: 'main',
        prepTime: 20,
        cookTime: 20,
        servings: 4,
        estimatedCost: 150000,
        difficulty: 'medium',
        tags: ['cuối tuần', 'đặc sản'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 380, protein: 30, carbs: 10, fat: 22, sodium: 500),
        ingredients: [
          IngredientModel(id: 'i54', name: 'Thịt ếch', quantity: 500, unit: 'g'),
          IngredientModel(id: 'i55', name: 'Nước cốt dừa', quantity: 150, unit: 'ml'),
          IngredientModel(id: 'i56', name: 'Bột cà ri', quantity: 1, unit: 'thìa'),
          IngredientModel(id: 'i57', name: 'Hành tây, mộc nhĩ, bún tàu', quantity: 100, unit: 'g'),
        ],
        instructions: [
          'Ếch làm sạch chặt miếng, ướp bột cà ri, hành tỏi, mắm.',
          'Phi hành sả thơm, xào ếch săn lại.',
          'Cho hành tây, mộc nhĩ ngâm nở vào xào.',
          'Đổ nước cốt dừa vào um lửa nhỏ.',
          'Gần chín cho bún tàu cắt khúc vào, rắc đậu phộng rang.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Mắm ruốc xào thịt ba rọi',
        description: 'Mắm ruốc đậm đà xào thịt sả ớt, ăn tốn cơm ngày mưa.',
        imageUrl: 'https://images.unsplash.com/photo-1626804475297-41609ea0f488?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'pork',
        mealType: 'main',
        prepTime: 10,
        cookTime: 25,
        servings: 4,
        estimatedCost: 85000,
        difficulty: 'easy',
        tags: ['đậm đà', 'tốn cơm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 450, protein: 18, carbs: 15, fat: 35, sodium: 1200),
        ingredients: [
          IngredientModel(id: 'i58', name: 'Thịt ba rọi băm hoặc xắt hạt lựu', quantity: 300, unit: 'g'),
          IngredientModel(id: 'i59', name: 'Mắm ruốc', quantity: 3, unit: 'thìa'),
          IngredientModel(id: 'i60', name: 'Sả băm, ớt, tỏi', quantity: 50, unit: 'g'),
          IngredientModel(id: 'i61', name: 'Đường', quantity: 3, unit: 'thìa'),
        ],
        instructions: [
          'Hòa mắm ruốc với xíu nước ấm cho tan.',
          'Xào thịt ba rọi ra mỡ, thêm sả tỏi ớt băm vào phi thơm.',
          'Đổ mắm ruốc vào xào lửa nhỏ.',
          'Thêm nhiều đường để dằn vị mặn, xào tới khi keo lại, màu sậm.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Cá hồi áp chảo sốt chanh dây',
        description: 'Cá hồi mềm béo kết hợp sốt chanh dây chua thanh sang trọng.',
        imageUrl: 'https://images.unsplash.com/photo-1599081577741-6949397f26d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'fish',
        mealType: 'main',
        prepTime: 10,
        cookTime: 15,
        servings: 2, // Món sang thường khẩu phần ít hơn
        estimatedCost: 250000,
        difficulty: 'medium',
        tags: ['cuối tuần', 'sang trọng', 'healthy'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 350, protein: 34, carbs: 15, fat: 18, sodium: 250),
        ingredients: [
          IngredientModel(id: 'i62', name: 'Cá hồi phi lê', quantity: 400, unit: 'g'),
          IngredientModel(id: 'i63', name: 'Chanh dây', quantity: 3, unit: 'quả'),
          IngredientModel(id: 'i64', name: 'Bơ lạt', quantity: 20, unit: 'g'),
          IngredientModel(id: 'i65', name: 'Đường, muối, tiêu', quantity: 1, unit: 'vừa đủ'),
        ],
        instructions: [
          'Ướp cá hồi với chút muối tiêu.',
          'Áp chảo cá hồi chín vàng đều 2 mặt với bơ lạt (đừng để quá chín).',
          'Lấy ruột chanh dây, lọc bỏ hạt nếu thích. Đun sôi với đường và xíu muối cho sệt lại.',
          'Rưới sốt chanh dây lên cá hồi và thưởng thức.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Vịt kho gừng',
        description: 'Vịt kho gừng thơm nồng, khử sạch mùi hôi.',
        imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'other',
        mealType: 'main',
        prepTime: 20,
        cookTime: 40,
        servings: 4,
        estimatedCost: 150000,
        difficulty: 'medium',
        tags: ['đậm đà', 'ấm áp'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 410, protein: 28, carbs: 8, fat: 28, sodium: 600),
        ingredients: [
          IngredientModel(id: 'i66', name: 'Thịt vịt', quantity: 600, unit: 'g'),
          IngredientModel(id: 'i67', name: 'Gừng đập dập', quantity: 50, unit: 'g'),
          IngredientModel(id: 'i68', name: 'Rượu trắng', quantity: 2, unit: 'thìa'),
        ],
        instructions: [
          'Rửa vịt với gừng và rượu trắng để khử mùi hôi, chặt miếng.',
          'Ướp vịt với mắm, đường, gừng, hành tỏi.',
          'Xào vịt săn lại, đổ xíu nước xâm xấp.',
          'Kho lửa nhỏ tới khi thịt vịt mềm rục, nước sệt lại.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Cá diêu hồng chưng tương',
        description: 'Cá hấp với tương hột, nấm, bún tàu béo ngậy bổ dưỡng.',
        imageUrl: 'https://images.unsplash.com/photo-1599081577741-6949397f26d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'fish',
        mealType: 'main',
        prepTime: 15,
        cookTime: 25,
        servings: 4,
        estimatedCost: 110000,
        difficulty: 'medium',
        tags: ['hấp', 'thanh đạm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 320, protein: 30, carbs: 20, fat: 12, sodium: 800),
        ingredients: [
          IngredientModel(id: 'i69', name: 'Cá diêu hồng', quantity: 800, unit: 'g'),
          IngredientModel(id: 'i70', name: 'Tương hột', quantity: 3, unit: 'thìa'),
          IngredientModel(id: 'i71', name: 'Nấm đông cô', quantity: 50, unit: 'g'),
          IngredientModel(id: 'i72', name: 'Bún tàu, nấm mèo', quantity: 30, unit: 'g'),
        ],
        instructions: [
          'Cá làm sạch, khía lằn chéo.',
          'Nấm ngâm nở thái sợi.',
          'Ướp cá với tương hột, đường, hành tỏi xào thơm.',
          'Xếp nấm, bún tàu quanh cá, đem chưng cách thủy 25 phút.',
        ],
      ),

      // ==========================================
      // 10 MÓN CANH (SOUP)
      // ==========================================
      MealModel(
        id: '',
        name: 'Canh rau ngót thịt bằm',
        description: 'Canh rau ngót thanh mát, thịt băm ngọt nước.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 10,
        cookTime: 10,
        servings: 4,
        estimatedCost: 40000,
        difficulty: 'easy',
        tags: ['thanh mát', 'nhanh'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 120, protein: 12, carbs: 8, fat: 5, sodium: 400),
        ingredients: [
          IngredientModel(id: 'i73', name: 'Rau ngót', quantity: 2, unit: 'bó'),
          IngredientModel(id: 'i74', name: 'Thịt heo băm', quantity: 150, unit: 'g'),
        ],
        instructions: [
          'Rau ngót tuốt lá, vò hơi nát để canh ngọt và lá mềm.',
          'Thịt băm ướp xíu hạt nêm.',
          'Đun sôi nước, cho thịt băm vào nấu chín hớt bọt.',
          'Thả rau ngót vào nấu khoảng 3 phút là được.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh chua cá lóc',
        description: 'Canh chua Nam Bộ chua ngọt thanh, chuẩn vị.',
        imageUrl: 'https://images.unsplash.com/photo-1599081577741-6949397f26d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 15,
        cookTime: 20,
        servings: 4,
        estimatedCost: 120000,
        difficulty: 'medium',
        tags: ['miền Nam', 'chua ngọt'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 220, protein: 20, carbs: 18, fat: 8, sodium: 500),
        ingredients: [
          IngredientModel(id: 'i75', name: 'Cá lóc', quantity: 500, unit: 'g'),
          IngredientModel(id: 'i76', name: 'Thơm, cà chua', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i77', name: 'Bạc hà, đậu bắp, giá', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i78', name: 'Me chua', quantity: 30, unit: 'g'),
          IngredientModel(id: 'i79', name: 'Rau nêm (ngò om, ngò gai)', quantity: 20, unit: 'g'),
        ],
        instructions: [
          'Cá làm sạch, khứa khúc, chiên sơ cho bớt tanh (tùy ý).',
          'Dầm me với nước nóng lấy nước cốt.',
          'Đun sôi nước, cho cá vào luộc chín vớt ra.',
          'Cho nước me, thơm, cà chua vào nồi đun sôi. Nêm đường, mắm cho chua ngọt đậm đà.',
          'Cho bạc hà, đậu bắp, giá vào. Tắt bếp rắc rau nêm.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh mướp mồng tơi tôm khô',
        description: 'Canh mướp thơm lừng, mồng tơi nhớt nhẹ dễ ăn.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 10,
        cookTime: 10,
        servings: 4,
        estimatedCost: 50000,
        difficulty: 'easy',
        tags: ['mùa hè', 'thanh mát'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 80, protein: 6, carbs: 12, fat: 1, sodium: 350),
        ingredients: [
          IngredientModel(id: 'i80', name: 'Mướp hương', quantity: 1, unit: 'quả'),
          IngredientModel(id: 'i81', name: 'Mồng tơi', quantity: 1, unit: 'bó'),
          IngredientModel(id: 'i82', name: 'Tôm khô', quantity: 30, unit: 'g'),
        ],
        instructions: [
          'Tôm khô ngâm nở, giã hơi nát.',
          'Mướp gọt vỏ thái xéo. Mồng tơi nhặt lá.',
          'Đun sôi nước với tôm khô.',
          'Cho mướp và mồng tơi vào, nêm hạt nêm, sôi bùng lên là tắt bếp.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh bí đỏ hầm xương',
        description: 'Bí đỏ bùi ngọt, xương heo hầm nhừ.',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-811114215443?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 10,
        cookTime: 40,
        servings: 4,
        estimatedCost: 90000,
        difficulty: 'medium',
        tags: ['bổ dưỡng', 'hầm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 280, protein: 18, carbs: 25, fat: 12, sodium: 400),
        ingredients: [
          IngredientModel(id: 'i83', name: 'Xương heo (xương cổ hoặc sườn non)', quantity: 400, unit: 'g'),
          IngredientModel(id: 'i84', name: 'Bí đỏ', quantity: 400, unit: 'g'),
        ],
        instructions: [
          'Xương chặt khúc, chần nước sôi rửa sạch.',
          'Hầm xương 30 phút lấy nước ngọt, vớt bọt liên tục.',
          'Bí đỏ gọt vỏ thái cục vuông to.',
          'Cho bí đỏ vào nồi hầm thêm 10 phút cho bí nhừ.',
          'Nêm gia vị vừa ăn, rắc ngò rí.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh cải thảo cuộn thịt',
        description: 'Thịt băm cuộn trong lá cải thảo thanh tao.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 20,
        cookTime: 15,
        servings: 4,
        estimatedCost: 70000,
        difficulty: 'medium',
        tags: ['đẹp mắt', 'thanh đạm'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 180, protein: 15, carbs: 10, fat: 8, sodium: 380),
        ingredients: [
          IngredientModel(id: 'i85', name: 'Cải thảo', quantity: 1, unit: 'bắp'),
          IngredientModel(id: 'i86', name: 'Thịt băm', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i87', name: 'Mộc nhĩ băm', quantity: 10, unit: 'g'),
        ],
        instructions: [
          'Tách từng lá cải thảo, chần qua nước sôi cho lá mềm.',
          'Trộn thịt băm, mộc nhĩ, gia vị.',
          'Trải lá cải thảo, cho nhân thịt vào cuộn lại.',
          'Đun sôi nước dùng (hoặc nước xương), thả các cuộn cải vào luộc chín.',
          'Nêm gia vị vừa ăn.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh tần ô (cải cúc) chả cá',
        description: 'Rau tần ô thơm đặc trưng nấu cùng chả cá dai giòn.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 10,
        cookTime: 10,
        servings: 4,
        estimatedCost: 65000,
        difficulty: 'easy',
        tags: ['nhanh gọn', 'giải nhiệt'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 150, protein: 14, carbs: 6, fat: 7, sodium: 450),
        ingredients: [
          IngredientModel(id: 'i88', name: 'Rau tần ô', quantity: 2, unit: 'bó'),
          IngredientModel(id: 'i89', name: 'Chả cá thác lác', quantity: 150, unit: 'g'),
        ],
        instructions: [
          'Chả cá ướp xíu tiêu, hành băm, mắm, quết cho dai.',
          'Đun sôi nước, dùng muỗng bắt từng viên chả cá thả vào.',
          'Chả cá nổi lên là chín, thả rau tần ô vào sôi bùng lên tắt bếp.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh khổ qua nhồi thịt',
        description: 'Món ăn không thể thiếu ngày Tết, vị đắng nhẹ hậu ngọt.',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-811114215443?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 20,
        cookTime: 40,
        servings: 4,
        estimatedCost: 80000,
        difficulty: 'medium',
        tags: ['truyền thống', 'thanh nhiệt'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 200, protein: 16, carbs: 12, fat: 10, sodium: 300),
        ingredients: [
          IngredientModel(id: 'i90', name: 'Khổ qua', quantity: 3, unit: 'quả'),
          IngredientModel(id: 'i91', name: 'Thịt xay', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i92', name: 'Nấm mèo, bún tàu', quantity: 20, unit: 'g'),
        ],
        instructions: [
          'Khổ qua mổ ruột, rửa sạch. Trộn thịt xay, nấm mèo, bún tàu nhồi vào khổ qua.',
          'Nấu nước sôi, thả khổ qua vào hầm.',
          'Hầm khoảng 30-40 phút cho khổ qua mềm rục.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh rau dền tôm tươi',
        description: 'Nước canh đỏ au bắt mắt, vị tôm ngọt xớt.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 15,
        cookTime: 10,
        servings: 4,
        estimatedCost: 75000,
        difficulty: 'easy',
        tags: ['đẹp mắt', 'ngọt nước'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 110, protein: 15, carbs: 8, fat: 2, sodium: 350),
        ingredients: [
          IngredientModel(id: 'i93', name: 'Rau dền đỏ', quantity: 2, unit: 'bó'),
          IngredientModel(id: 'i94', name: 'Tôm sú tươi', quantity: 200, unit: 'g'),
        ],
        instructions: [
          'Tôm lột vỏ, rút chỉ đen, băm sơ hoặc để nguyên con.',
          'Đun sôi nước, cho tôm vào nấu chín.',
          'Thả rau dền vào, nêm hạt nêm, chờ sôi lại tắt bếp.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh hến nấu bầu',
        description: 'Vị hến miền Trung thanh mát, ngọt nước vô cùng.',
        imageUrl: 'https://images.unsplash.com/photo-1599081577741-6949397f26d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 15,
        cookTime: 15,
        servings: 4,
        estimatedCost: 65000,
        difficulty: 'medium',
        tags: ['miền Trung', 'giải nhiệt'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 90, protein: 10, carbs: 10, fat: 1, sodium: 300),
        ingredients: [
          IngredientModel(id: 'i95', name: 'Thịt hến', quantity: 200, unit: 'g'),
          IngredientModel(id: 'i96', name: 'Bầu', quantity: 1, unit: 'trái'),
          IngredientModel(id: 'i97', name: 'Rau thì là, hành lá', quantity: 1, unit: 'ít'),
        ],
        instructions: [
          'Hến rửa sạch. Bầu băm sợi hoặc thái lát.',
          'Phi hành thơm xào hến nhanh tay.',
          'Cho nước vào đun sôi, thả bầu vào.',
          'Bầu chín tới nêm gia vị, rắc thì là hành lá.',
        ],
      ),
      MealModel(
        id: '',
        name: 'Canh kim chi thịt đậu hũ',
        description: 'Canh chuẩn vị Hàn Quốc chua cay kích thích vị giác.',
        imageUrl: 'https://images.unsplash.com/photo-1582169505937-b9992bd01ed9?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        category: 'soup',
        mealType: 'soup',
        prepTime: 10,
        cookTime: 15,
        servings: 4,
        estimatedCost: 95000,
        difficulty: 'easy',
        tags: ['Hàn Quốc', 'cay', 'ngày lạnh'],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        nutrition: NutritionModel(calories: 280, protein: 18, carbs: 15, fat: 16, sodium: 800),
        ingredients: [
          IngredientModel(id: 'i98', name: 'Kim chi cải thảo', quantity: 300, unit: 'g'),
          IngredientModel(id: 'i99', name: 'Thịt ba chỉ', quantity: 150, unit: 'g'),
          IngredientModel(id: 'i100', name: 'Đậu hũ non', quantity: 1, unit: 'hộp'),
        ],
        instructions: [
          'Xào thịt ba chỉ cho ra mỡ, thêm kim chi vào xào cùng.',
          'Đổ nước vào nấu sôi 10 phút để ra vị chua.',
          'Cắt đậu hũ non thành khối thả vào canh đun thêm 3 phút.',
          'Rắc hành lá, tắt bếp.',
        ],
      ),
    ];

    int count = 0;
    for (var meal in meals) {
      await service.createMeal(meal);
      count++;
      print('Added: ${meal.name} ($count/30)');
    }
    print('Seeding completed! 30 meals imported.');
  }
}
